// packages/todo-react-redux/src/App.js
import React, { useState } from 'react';
import { connect } from 'react-redux'
import { Button, Input, List, Icon } from 'antd';
import './App.css';

export default connect(
  state => ({
    list: state.list
  })
)( props => {
  const [state, setState] = useState('');
  return (
    <div className="App">
      <Input value={state} onChange={e => setState(e.target.value)}/>
      <Button type="primary" onClick={() => {
        window.todo.add({ text: state });
        setState('');
      }}>Add</Button>
      <List
        bordered
        dataSource={props.list}
        renderItem={(item, index) => 
          <List.Item
            key={index}>
            <Icon type="close" onClick={() => window.todo.remove(index)}  />
            <span
              style={{textDecoration: item.completed ? 'line-through' : ''}}
              onClick={() => window.todo.toggle(index)}>
              {item.text}
            </span>
          </List.Item>
        }
      />
    </div>
  )
});

// packages/todo-ng/src/app/app.component.ts
import { Component } from '@angular/core';

import { TodoService } from './todo.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  input: string;
  constructor(
    public todoService: TodoService
  ) {}

  add(text) {
    this.todoService.add({ text, completed: false });
    this.input = '';
  }
}

<div>
  <input nz-input [(ngModel)]="input">
  <button nz-button nzType="primary" (click)="add(input)">Add</button>
  <nz-list
    nzBordered>
    <nz-list-item
      *ngFor="let item of todoService.list;let i = index"
      [nzContent]="item.text"
      [ngStyle]="{'text-decoration': item.completed ? 'line-through' : ''}"
      (click)="todoService.toggle(i)">
      <i nz-icon type="close" theme="outline" (click)="todoService.remove(i)"></i>
    </nz-list-item>
  </nz-list>
</div>
