// packages/todo-react-mobx/src/App.js
import React, { useState } from 'react';
import { Button, Input, List, Icon } from 'antd';
import { observer } from 'mobx-react'
import './App.css';

const TodoList = observer((props) => 
  <>
    <List
      bordered>
      {
        // mobx for ant list bugs.
        props.todo.list.map((item, index) =>
          <List.Item
            key={index}>
            <Icon type="close" onClick={() => window.todo.remove(index)}  />
            <span
              style={{textDecoration: item.completed ? 'line-through' : ''}}
              onClick={() => window.todo.toggle(index)}>
              {item.text}
            </span>
          </List.Item>
        )
      }
    </List>
    <b onClick={() => props.todo.increase()}>{props.todo.count}</b>
  </>
);


export default ( props => {
  const [state, setState] = useState(''); 
  return (
    <div className="App">
      <Input value={state} onChange={e => setState(e.target.value)}/>
      <Button type="primary" onClick={() => {
        window.todo.add({ text: state });
        setState('');
      }}>Add</Button>
      <TodoList todo={props.todo}/>
    </div>
  )
});

// packages/todo-vue/src/App.vue
<template>
  <div id="app">
    <a-input v-model="input"/>
    <a-button type="primary" @click="addTodo">Add</a-button>
    <a-list
      bordered
      :dataSource="list">
      <a-list-item
        slot="renderItem"
        slot-scope="item, index">
        <a-icon type="close" @click="removeTodo(index)" />
        <span
          :style="{textDecoration: item.completed ? 'line-through' : ''}" 
          @click="toggleTodo(index)">
          {{item.text}}
        </span>
      </a-list-item>
    </a-list>
    <b @click="increase()">{{count}}</b>
  </div>
</template>

<script>

export default {
  name: 'app',
  data () {
    return {
      input: '',
      list: this.$store.state.list,
      count: this.$store.getters.count,
    }
  },
  methods: {
    addTodo() {
      window.todo.add({ text: this.input, completed: false });
      this.input = '';
    },
    toggleTodo(index) {
      window.todo.toggle(index);
    },
    removeTodo(index) {
      window.todo.remove(index);
    },
    increase() {
      window.todo.increase();
    }
  }  
}
</script>
