// todo-react-mobx/src/App.js
import React, { useState } from 'react';
import { Button, Input, List } from 'antd';
import { observer } from 'mobx-react'
import './App.css';

const TodoList = observer((props) => 
  <List bordered>
  {
    props.todo.list.map((item, index) =>
      <List.Item
        key={index}
        style={{textDecoration: item.completed ? 'line-through' : ''}}
        onClick={() => window.todo.toggle(index)}>
        {item.text}
      </List.Item>
    )
  }
  </List>
);

export default ( props => {
  const [state, setState] = useState(''); 
  return (
    <div className="App">
      <Input value={state} onChange={e => setState(e.target.value)}/>
      <Button type="primary" onClick={() => {
        window.todo.add({ text: state });
        setState('');
      }}>Add</Button>
      <TodoList todo={props.todo}/>
    </div>
  )
});

// packages/todo-vue/src/App.vue
<template>
  <div id="app">
    <a-input v-model="input"/>
    <a-button type="primary" @click="addTodo">Add</a-button>
    <a-list
      bordered
      :dataSource="list">
      <a-list-item
        slot="renderItem"
        slot-scope="item, index"
        :style="{textDecoration: item.completed ? 'line-through' : ''}" 
        @click="toggleTodo(index)">
        {{item.text}}
      </a-list-item>
    </a-list>
  </div>
</template>

<script>

export default {
  name: 'app',
  data () {
    return {
      input: '',
      list: this.$store.state.list,
    }
  },
  methods: {
    addTodo() {
      window.todo.add({ text: this.input, completed: false });
      this.input = '';
    },
    toggleTodo(index) {
      window.todo.toggle(index);
    }
  }  
}
</script>
