// todo-vue/src/App.vue
<template>
  <div id="app">
    <a-input v-model="input"/>
    <a-button type="primary" @click="addTodo">Add</a-button>
    <a-list
      bordered
      :dataSource="list">
      <a-list-item
        slot="renderItem"
        slot-scope="item, index"
        v-bind:style="{textDecoration: item.completed ? 'line-through' : ''}" 
        @click="toggleTodo(index)">
        {{item.text}}
      </a-list-item>
    </a-list>
  </div>
</template>

<script>

export default {
  name: 'app',
  data () {
    return {
      input: '',
      list: this.$store.state.list,
    }
  },
  methods: {
    addTodo() {
      window.todo.add({ text: this.input, completed: false });
      this.input = '';
    },
    toggleTodo(index) {
      window.todo.toggle(index);
    }
  }  
}
</script>

// packages/todo-react-redux/src/App.js
import React, { useState } from 'react';
import { connect } from 'react-redux'
import { Button, Input, List } from 'antd';
import './App.css';

export default connect(
  state => ({
    list: state.list
  })
)( props => {
  const [state, setState] = useState('');
  return (
    <div className="App">
      <Input value={state} onChange={e => setState(e.target.value)}/>
      <Button type="primary" onClick={() => {
        window.todo.add({ text: state });
        setState('');
      }}>Add</Button>
      <List
        bordered
        dataSource={props.list}
        renderItem={(item, index) => 
          <List.Item 
            style={{textDecoration: item.completed ? 'line-through' : ''}}
            onClick={() => window.todo.toggle(index)}>
            {item.text}
          </List.Item>
        }
      />
    </div>
  )
});
