// todo-react-redux/src/App.js
import React, { Component } from 'react';
import { Button, Input, List } from 'antd';
import './App.css';

const data = [
  'Racing car sprays burning fuel into crowd.',
  'Japanese princess to wed commoner.',
  'Australian walks 100km after outback crash.',
  'Man charged over missing wedding girl.',
  'Los Angeles battles huge wildfires.',
];

class App extends Component {
  render() {
    return (
      <div className="App">
        <Input />
        <Button type="primary">Button</Button>
        <List
          bordered
          dataSource={data}
          renderItem={item => (<List.Item>{item}</List.Item>)}
        />
      </div>
    );
  }
}

export default App;

// todo-ng/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  value: string;
  data = [
    'Racing car sprays burning fuel into crowd.',
    'Japanese princess to wed commoner.',
    'Australian walks 100km after outback crash.',
    'Man charged over missing wedding girl.',
    'Los Angeles battles huge wildfires.'
  ];
}

<div>
  <input nz-input placeholder="Basic usage" [(ngModel)]="value">
  <button nz-button nzType="primary">Primary</button>
  <nz-list [nzDataSource]="data" nzBordered
           [nzHeader]="'Header'" [nzFooter]="'Footer'"
           [nzRenderItem]="item">
    <ng-template #item let-item><nz-list-item [nzContent]="item"></nz-list-item></ng-template>
  </nz-list>
</div>
